jobs:
  - job: Build_Ubuntu1604
    pool:
      vmImage: ubuntu-16.04
    steps:
    # Install and run vcsim Docker container
    # "--ds 2" creates two datastores instead of the default one
    - script: |
        docker run --rm -d -p 443:443/tcp nimmis/vcsim --ds 2
      displayName: 'Run vCenter Simulator container'
    # Run Pester tests
    - script: |
        pwsh -c '.\build.ps1'
      displayName: 'Build and Test'
    # Analyze test results
    - task: PublishTestResults@2
      inputs:
        testRunner: 'NUnit'
        testResultsFiles: '**/TestResults.xml'
        testRunTitle: 'Ubuntu1604'
      displayName: 'Publish Test Results'
